OUTPUT:
    OUTPUT_DIR: "output/"
INPUT:
  #GT_FILEPATH: "/cis/net/r22a/data/vshenoy/merl/MMSE_HR_GT/MMSE_HR_processed_all_subjects_missing_face_untested/40_Subjects_GT_all_cases/"
  #TIME_SERIES_FILEPATH: "/cis/net/r22a/data/vshenoy/merl/time_series_results/biosignals_time_series/unrolled-ippg-time_series/time_series"
  TRAIN_JSON_PATH: "/cis/home/vshenoy/durr_hand/Physnet_Ischemia/hand_ischemia/data/data_subset.json"
  TEST_JSON_PATH: "/cis/home/vshenoy/durr_hand/Physnet_Ischemia/hand_ischemia/data/data_subset.json"
  #TEST_JSON_PATH: "/cis/home/vshenoy/durr_hand/Physnet_Ischemia/hand_ischemia/data/tourniquet_ischemia.json"
TIME_SCALE_PPG:
  FPS: 30
  PASSBAND_FREQ: 36
  CUTOFF_FREQ: 500
  NUM_TAPS: 5
  FRAME_STRIDE: 2.0 #units: seconds
  FRAME_STRIDE_TEST: 10.0 #units: seconds
  MIN_WINDOW_SEC: 10.0
  TIME_WINDOW_SEC: 29.0
  USE_DENOISER: True
  CLS_MODEL_TYPE: "SPEC"
DENOISER:
  BATCH_SIZE: 2
  EPOCHS: 20
  LR: 0.00005
  WEIGHT_DECAY: 0.0
  SCHEDULER_MILESTONE: 20
TEST:
  EVAL_PERIOD: 1
  PLOT_INPUT_OUTPUT: False